// class Node{
//     constructor(d){
//         this.data=d
//         this.next =null
//         this.pre=null
//     }
// }
// class linkedlist{
//     constructor(node){
//         this.head=node
//         this.tail=node
//     }
//     size=function(){
//         let tempnode=this.head
//         let length=0
//         while(tempnode!==null){
//             length++
//             tempnode = tempnode.next 

//         }
//         return length
//     }
//     print =function(){
//         let currentnode=this.head;
//         while(currentnode!==null){
//             console.log(currentnode.data)
//             currentnode=currentnode
//         }
//     }
// }
if(!null){
    console.log("yes this work")
}
else { console.log("nothing happens")}

